name: Go
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: go1.25.0+auto
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25.x"

      - name: Test with coverage
        run: GI_CALL=out.dot GI_AST=test.ast GI_TRACE=1 go test -v -coverprofile=coverage.txt ./internal

      - name: Report coverage
        run: go tool cover -func=coverage.txt

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: emicklei/gi

      - name: Run examples
        run: make examples

      - name: Run GoByExample tests
        run: make gobyexample

      - name: Publish Treerunner report to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"
        run: |
          aws s3 sync gobyexample/examples/output s3://${{ secrets.AWS_BUCKET }}
