name: Go
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: go1.25.0+auto
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25.x"

      - name: Test with coverage
        run: go test -v -coverprofile=coverage.txt ./internal

      - name: Report coverage
        run: go tool cover -func=coverage.txt

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: emicklei/gi
      
      - name: Run examples
        run: make examples

      - name: Run GoByExample tests
        run: make gobyexample

      - name: Publish GoByExample result
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: gobyexample/examples/output